### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by johko** [huggingface/hffs#11]
Maybe I'm a bit too early, but should the `pip install hffs` command already work? Because for me it is not:
```
ERROR: Could not find a version that satisfies the requirement hffs (from versions: none)
ERROR: No matching distribution found for hffs
```

**Comment by Wauplin** [comment]
Hi @johko, `hffs` is not released soon but should be soon (cc @mariosasko).
However, you can already install it from github if you'd like :)

```
pip install git+https://github.com/huggingface/hffs
```

**Comment by johko** [comment]
All good, I just wondered because the pip install was already in the README. 
But the whole project is a great idea in general and quite helpful  :hugs:
