### ISSUE TITLE
Don't specify `repo_id` in `__init__` for consistency with s3fs, gcsfs, etc.

### ISSUE THREAD

**Issue by lhoestq** [huggingface/hffs#17]
Those filesystems can be instantiated without specifying a repo id.

We could have the same to let users familiar with s3fs, gcsfs, etc. start playing with `hffs` directly, by transposing what they know already about common filesystem implementations

Related to https://github.com/huggingface/moon-landing/issues/5690

**Comment by lhoestq** [comment]
assigning myself to play with this logic, see how feasible it is

**Comment by mariosasko** [comment]
I think canonical repos are stopping us from implementing this (when splitting on "/",  `repo_id` is  either contained in one or two "URL parts")

**Comment by lhoestq** [comment]
I think we can workaround this by checking if the repo_id with namespace exists first, and fallback on the repo_id without namespace otherwise

**Comment by Wauplin** [comment]
Out of curiosity, what are we talking about when you say "without repo_id" ? The user have to provide some information at some point, isn't it? Do you mean concatenating repo type + repo_id + path_in_repo in a single string ?

**Comment by lhoestq** [comment]
Something like
```python
fs = HfFileSystem(token=token)
fs.glob("gpt2/*.bin")
```
and for datasets:
```python
fs = HfFileSystem(token=token)
fs.glob("datasets/my-username/my-dataset/*.csv")
```
