### ISSUE TITLE
Optimize repo siblings cache control

### ISSUE THREAD

**Issue by mariosasko** [huggingface/hffs#5]
Currently, we fetch all the siblings of a repo after each modification, which can be problematic for repos with many files due to the size of the returned payload. We can optimize this by fetching only the siblings of the repo directories affected by a particular modification. For this to be added, server-side querying of the repo siblings would need to be implemented (+ accompanying `hfh` API). (cc @julien-c @SBrandeis @Wauplin )

**Comment by mariosasko** [comment]
@coyotte508 Unfortunately, it looks like it's not possible to fetch the folder's entries' info in one API call with the `paths-info` endpoint. Could this feature (e.g., data param `recursive`) be added to the API to allow me to address this issue before the "official" release? (my bad for not asking for this feature in the  `paths-info` PR)

**Comment by coyotte508** [comment]
Would this work:

- one `paths-info` to list all the paths
- for each path that is a folder, call `indexTree` with `recursive=true` (and paginate it) 

The second step can be parallelized, so it'd be two steps max.

On our side the `indexTree` endpoint is implemented differently, there's also the pagination logic inside it.
