### ISSUE TITLE
Default value of `repo_type` in `HfFilesystem.__init__` (and in `hfh`)

### ISSUE THREAD

**Issue by mariosasko** [huggingface/hffs#8]
@lhoestq thinks models' users should use `hfh` and not `hffs`, so he believes it would make more sense to change the default value of  `repo_type` to "dataset" to avoid having to explicitly pass `repo_type="dataset"` to `pandas.read_<format>` for instance. However, this would mean `hfh` and `hffs` are no longer aligned when it comes to `repo_type`'s default value (None/"model" vs. "dataset").

To preserve consistency (and to make this part more convenient), perhaps we could infer the repo type of a repo id if `repo_type=None` instead of defaulting to "model"? Of course, this would only be possible in scenarios where the repo id is not ambiguous.

Also, this would help us avoid situations like these in the future:
https://discuss.huggingface.co/t/huggingface-hub-upload-file-returns-a-404-error/16014
https://discuss.huggingface.co/t/upload-file-api-for-saving-to-persistent-datasets-on-hf-spaces/23689

cc @Wauplin @julien-c

**Comment by julien-c** [comment]
i didn't read in a ton of detail, but in any case, yes the following looks quite good to me:

```py
pd.read_parquet("hf://datasets/username/my-dataset")
```

(BTW if we re-did `hfh` now we probably wouldn't have a default value for `repo_type` – i.e. you would need to explicitly specific `model`)
